<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?= BASE_URL ?>">
    <link rel="stylesheet" href="css/carrefy.css">
    <link rel="icon" href="img/faviconCarrefy.png" type="image/x-icon"> 
    <title>Carrefy</title>
</head>
<header>
    <a id="no-btn" href="<?=BASE_URL?>home"> <img id="logo" src="img/CarrefyLogo.png" alt="carrefylogo"> </a>
</header>

<body>
 <main>