<?php require 'templates/header.phtml'; ?>

<nav>
    <a href="<?=BASE_URL?>login">Acceder como administrador</a></li>
</nav>

<h3>Detalle del producto:</h2>
    <ul>
        <?php foreach($products as $product): ?>
        <h4>Nombre: <?= $product->product_name?></h4>
        <li>Categoría: <?= $product->category_name?></li>
        <li>Cantidad disponible: <?= $product->product_stock?></li>
        <li>Precio: $<?= $product->product_price?></li>
        <?php endforeach ?>
    </ul>

<a href="<?=BASE_URL?>products-list">Volver al listado</a>
<a href="<?=BASE_URL?>home">Volver al inicio</a>

<?php require 'templates/footer.phtml'; ?>