<?php require 'templates/header.phtml'; ?>

<h3>Modificar producto</h3>

<form action='update-product/<?=$id?>' method='POST'>
    <div>
        <label>Nuevo nombre del producto: </label>
        <input name='name' type='text' value='name' required>
    </div>
    <div>
        <label>Categoría a la que pertenece el producto: </label>
        <select name="category" required>
                <?php foreach($categories as $category):?>
                <option value='<?=$category->category_id?>'><?=$category->category_name?></option>
                <?php endforeach ?>
        </select>
    </div>
    <div>
        <label>Precio: </label>
        <input name='price' type='double' value='price' required>
    </div>
    <div>
        <label>Cantidad: </label>
        <input name='stock' type='number' value='quantity' required>
    </div>

    <button type='submit'>Editar producto</button>
</form>

<button> <a href="<?=BASE_URL?>products-list">Volver al listado</a>
<button> <a href="<?=BASE_URL?>home">Volver al inicio</a>


<?php require 'templates/footer.phtml'; ?>